# Generated by Django 3.1.6 on 2021-02-09 14:32

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210209_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='accounts/ankit/profile.png', upload_to=accounts.models.upload_location),
        ),
    ]
